### ISSUE TITLE
On My Account Page, the linkable text is not very obvious

### ISSUE THREAD

**Issue by taeche** [taeche/SoDoEx#13]
SUMMARY:
The hyperlink text are not very obvious and requires additional text formatting.

REPRO:
1. Navigate to the My Account 
2. Log on

ACTUAL RESULTS:
The "Sign out" and "edit your password and account details." have the same text format as other text and it's not easily distinguishable

EXPECTED RESULTS:
The "Sign out" and "edit your password and account details." should follow the hyperlink formatting standard.

**Comment by daypekr** [comment]
Fixed and deployed to DEV site.
Since a css file modified, please refresh several times when you connect the my account page to check this out, so the browser load modified css rather than the cashed one.

**Comment by daypekr** [comment]
Can I deploy this to the Production?

**Comment by taeche** [comment]
It's too dark.  Let's use lighter blue like the link below.  view it on GitHub

Date: Fri, 18 Mar 2016 00:24:32 -0700

**Comment by daypekr** [comment]
The link color is the same as _view it on GitHub_. 
It is default link color of HTML document. 
The thing is that I set them Bold to emphasize which cause you to feel them darker.

I removed the Bold and added underline so that users can be noticed them as links intuitively.

Please check it out on DEV site.

FYI:

Without underline:
![image](https://cloud.githubusercontent.com/assets/8378894/13897354/48ad5cfe-edf2-11e5-9da3-ad35684fb505.png)

With underline:
![image](https://cloud.githubusercontent.com/assets/8378894/13897358/516a6792-edf2-11e5-8d4f-b8e764ca2102.png)

**Comment by taeche** [comment]
Looks better.  Ship it.

Date: Sat, 19 Mar 2016 00:48:20 -0700

**Comment by daypekr** [comment]
Deployed to production.
