### ISSUE TITLE
Remove Case of 12, 300ml from the wholesaler view

### ISSUE THREAD

**Issue by taeche** [taeche/SoDoEx#18]
The Wholesaler should only see the master case (Case of 72).  It needs to be consistent with 500ml

**Comment by taeche** [comment]
And the Retailer View.

**Comment by daypekr** [comment]
Fixed in DEV site.
Please check it out.

**Comment by taeche** [comment]
Looks good.  
When are we going to upgrade all WP and plug ins to the latest version?

Date: Sun, 10 Apr 2016 01:09:19 -0700

**Comment by daypekr** [comment]
Let me deploy this to production in today(midnight American time).

I am thinking of upgrading Wordpress and plugins in this weekend.
But, some of the plugins are not upgradeable as they customized for sodoex.com.
In Wordpress world, they support child theme mechanism, but don't support child plugins mechanism.
That's why I modified original plugins,which implies that modification will be overridden if we upgrade them.
For these plugins, the best option for us is that simply changing their name to prevent upgrade notice, 
and keep them as current version.
What do you think?

**Comment by daypekr** [comment]
Deployed to production.
Please check it out.

**Comment by taeche** [comment]
verified.

Date: Mon, 11 Apr 2016 07:30:55 -0700

**Comment by taeche** [comment]
Let's not rename them yet.  
Just keep a list of plugins that cannot be upgraded.

Date: Mon, 11 Apr 2016 01:06:52 -0700

**Comment by daypekr** [comment]
ok
