### ISSUE TITLE
Defect: Assigning Marker Colors for Store and Wholesale does not get reflect on the map

### ISSUE THREAD

**Issue by taeche** [taeche/SoDoEx#6]
Repro Steps:
1) Navigate to the Admin screen
2) Select Store -> Settings
3) Scroll down to Markers section
4) Select different marker colors for Store and Wholesale
5) Save and navigate to the Store link from the main web site

Expected Results:
Select marker colors get used to display the stores/wholesalers on the map

Actual Results:
The colors are static and do not change with the admin selection

**Comment by taeche** [comment]
Also in Production, the category is called "Retail" in case you are hard coding.

**Comment by daypekr** [comment]
Sorry for not giving you the detailed instruction to test the feature.

Marker color can be selected in **Store Categories** menu, NOT in the Settings menu.
I added the feature to the Store Categories menu to give it more flexibility.
As the result, it is not fixed with only 2 marker color such as "Store" and "Wholesale", but working with Categories which enables each category can have its own marker color.

You can edit marker color in the category edit page, as well as you can add new category with   marker color option.

**NOTE1**: Category name is not hard coded, but comes from the values of Store Categories.

**NOTE2 *_:  *_Wholesale location marker** in the settings is TODO feature by the original plugin developer,but somehow revealed which seems to be a bug. Let me hide it.
![image](https://cloud.githubusercontent.com/assets/8378894/13381070/36ba56a8-de95-11e5-92eb-2635553dc8de.png)

## Test steps:

1.Go to Store Categories menu under the Store Locator and click Edit of a category.
![image](https://cloud.githubusercontent.com/assets/8378894/13381079/712847fa-de95-11e5-978b-d3db26f5b29a.png)
2. Select proper marker  and save.
![image](https://cloud.githubusercontent.com/assets/8378894/13381089/9d315bc0-de95-11e5-939f-f695e19c3e64.png)
3. Check the result in the user screen.

**Comment by daypekr** [comment]
Is this issue verified too? Can I deploy this to the production?

**Comment by taeche** [comment]
verified.  move to production
